### ISSUE TITLE
Sleep interrupt esp_sleep_enable_ext1_wakeup

### ISSUE THREAD

**Issue by yacubovvs** [Open-Smartwatch/open-smartwatch-light#10]
It is not possible to use a mask to interrupt sleep by pressing all the buttons. GPIO13 and GPIO10 are not RTC_PINs.
It's a good idea to change the contacts, perhaps to GPIO27 and GPIO14. And reverse GPIO00 to another pin. The wake-up mode esc_sleep_enable_ext 1_wakeup only works with "any high output", but GPIO00 is still HIGH when not pressed

**Comment by uvwxy** [comment]
Thanks for your input. I have changed this with the latest version I am working on!
