### ISSUE TITLE
Change  screen led current

### ISSUE THREAD

**Issue by yacubovvs** [Open-Smartwatch/open-smartwatch-light#11]
It may be worth adding another mosfet 2N7002 and making 2 channels for controlling the backlight PIN_LED1 and PIN_LED 2 with current-limiting resistors 30 and 83 ohms. The combination of enabling these ports will allow to limit the backlight current to one of the following values - 22 ohms, 30 ohms, 83 ohms or infinite resistance (for power off). This will reduce the backlight current by 3.7 times in energy-saving mode.

This will be useful because the PWM of the ESP 32 does not work in sleep mode

**Comment by uvwxy** [comment]
I ran out of space on the PCB of the Light Revision 4.2...
