### ISSUE TITLE
Feature: Wireless Charging

### ISSUE THREAD

**Issue by Electro707** [Open-Smartwatch/open-smartwatch-light#4]
I think that a wireless charger built-in would be handy for everyday smartwatch usage. Preferably it should be Qi compliant so that any regular charger will work. Something like the [BQ51013B](https://www.ti.com/lit/ds/symlink/bq51013b.pdf?ts=1618083252163&ref_url=https%253A%252F%252Fwww.ti.com%252Fsitesearch%252Fdocs%252Funiversalsearch.tsp%253FsearchTerm%253Dqi%2Breceiver) or the [bq5105xB](https://www.ti.com/lit/ds/symlink/bq51050b.pdf?HQS=dis-dk-null-digikeymode-dsf-pf-null-wwe&ts=1618078894402) should work fine. Space on the board might be troublesome tough.

**Comment by uvwxy** [comment]
Currently, in the deep sleep and tap to wake up configuration the battery can last over a week.

I'd prefer a magnetic clip/external interface versus wireless charging, especially due to the size constraints.

Maybe for a Version 4/ Version 5 :)

**Comment by Tomaskocarter** [comment]
The only real benefit to wireless charging would be the increased water resistance imo.

**Comment by uvwxy** [comment]
There will be pads on the back to attach an arbitrary charging solution (wireless or magnetic contacts).
