### ISSUE TITLE
Creating a smartphone App for the watch

### ISSUE THREAD

**Issue by kekko7072** [Open-Smartwatch/open-smartwatch-light#7]
Hey I really like this open-sourche project. 
I like to contribute developing a mobile phone app (using flutter) to connect the watch to iOS/Android smartphone. 
To start using the clock and creating the app I will buy it from makerfabs the light edition and start developing.
 
I can comunicate with the watch through bluetooth, right?

Sensor now available:
+ Pedometer

In this first version of the app my goals will be:
+ Create a stable protocol of connection
+ Show Pedometer data in the app
+ Integration with Health Kit (Apple) and Google Fit.

For the future I'd like to use the data from this sensor:
+ Pulse sensor
+ Blood Oxygen Saturation
+ Altitude (I think is just in GPS version)

Using this sensor, In this second version of the app my goals will be:
+ Create sport watch  functions (ex. running)
+ Start showing notifications

I will develop it as open-source creating a mine Git repo for the project, when it will be stable and useful you could add to this git repo.
I 'm very excited for this new journey ;)

**Comment by kekko7072** [comment]
Hey how can I enable Bluetooth on the watch ?

**Comment by kekko7072** [comment]
Is BLE?

**Comment by uvwxy** [comment]
> Hey how can I enable Bluetooth on the watch ?

Take a look at `src/apps/tools/ble_media_ctrl.cpp` as an example for a BLE app on the OSW. Make sure to disable/resize the screen buffer (like this example app) to have enough free memory for the BLE software stack on the ESP32.

(The next versions of the watch will have +2mb ram to solve this issue)

Another example is: https://github.com/SeanReg/open-smartwatch-os/commit/9464d2418e018018ba23f9c36357525ee7722e2f

**Comment by kekko7072** [comment]
@uvwxy Thanks for the example, I will start from that. But can you explain me or there is a guide I can follow to start building app for the OSW? Because I'm trying to reverse engineer the OSW but I'm not able to understand where to start to code and make my app run in the OSW, I mean where should I add in the main to access it?

**Comment by RuffaloLavoisier** [comment]
@kekko7072 Could you add me in the Discord?

**Comment by kekko7072** [comment]
Sure my discord is kekko7072#2399 I'm already in the discord channel but I'm not ver active.

**Comment by kekko7072** [comment]
@RuffaloLavoisier Are you able to wright and build ble code for OSW, I'm trying to connect but with not so much success? 
Having a starting point for my code could help me with the OSW part of this integration.

**Comment by RuffaloLavoisier** [comment]
@kekko7072 Can you please leave a message? I send discord to you. Plz check it.

**Comment by yacubovvs** [comment]
> @uvwxy Thanks for the example, I will start from that. But can you explain me or there is a guide I can follow to start building app for the OSW? Because I'm trying to reverse engineer the OSW but I'm not able to understand where to start to code and make my app run in the OSW, I mean where should I add in the main to access it?

https://github.com/yacubovvs/CubOS/tree/main/tools/CubOSBLEApp  - Android example for arduino esp32 watch via BLE. Not best example, but it works

**Comment by kekko7072** [comment]
@yacubovvs thankyou but I mean app written for the OS of the watch, in c++ or other languages supported by the watch.
